<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'article' => 
  array (
    'article_blog_list' => 'Blog - List',
    'article_blog_post' => 'Blog - Single post',
  ),
  'page' => 
  array (
    'page_blog' => 'Blog - List',
    'page' => 'Page',
  ),
);


/* End of file views.php */
/* Auto generated by Themes Administration on : 2011.04.17 00:20:30 */
/* Location: /var/www/ionize/application/../themes/showcase/config/views.php */
