<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page_blog_view_post' => 'Blog Post view',
    'page_blog_view' => 'Blog view',
    'page' => 'Page',
  ),
);


/* End of file views.php */
/* Auto generated by Themes Administration on : 2011.02.09 09:38:46 */
/* Location: application/../themes/default/config/views.php */
