<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'article' => 
  array (
    'article_form_contact' => 'Contact Form',
    'article_blog_post_detail' => 'Post Detail',
    'article_blog_post_list' => 'Post in a list',
  ),
  'page' => 
  array (
    'page_blog' => 'Blog',
    'page_blog_post' => 'Blog Post',
    'page_contact' => 'Contact',
    'page_home' => 'Home',
    'page' => 'Page',
  ),
);


/* End of file views.php */
/* Auto generated by Themes Administration on : 2012.08.15 22:57:25 */
/* Location: /Users/Partikule/Sites/02.Test/ionize-test/application/../themes/fundation/config/views.php */
