<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page' => 'Page',
  ),
);


/* End of file views.php */
/* Auto generated by Themes Administration on : 2011.07.05 14:32:51 */
/* Location: /Volumes/Data/Sites/ionize-with_ci2/application/../themes/default/config/views.php */
