<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page' => 'Page',
    'shop/page_shop' => 'Shop',
    'shop/page_shop_cart' => 'Shop Cart',
    'shop/page_shop_checkout' => 'Shop Checkout',
    'shop/page_shop_confirmation' => 'Shop Confirmation',
  ),
);


/* End of file views.php */
/* Auto generated by Themes Administration on : 2012.04.07 13:16:10 */
/* Location: /Volumes/Data/Sites/ionize/application/../themes/fundation/config/views.php */
