<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    404 => '404',
    'page_blog' => 'Page Blog',
    'page_home' => 'Page Home',
    'page_search_result' => 'Page Search Results',
  ),
  'article' => 
  array (
    'article_blog_post_detail' => 'Blog Post',
    'article_blog_post_list' => 'Blog Post List',
    'article_footer' => 'Footer',
    'article_footer_twitter' => 'Footer Twitter',
    'article_picture_gallery' => 'Picture Gallery',
  ),
);


/* End of file views.php */
/* Auto generated by Themes Administration on : 2011.08.24 22:51:04 */
/* Location: /Volumes/Data/Sites/ionize-with_ci2/application/../themes/demo/config/views.php */
