<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page_home' => 'Page Home',
    'page_search_result' => 'Page Search Results',
  ),
);


/* End of file views.php */
/* Auto generated by Themes Administration on : 2011.07.12 18:44:21 */
/* Location: /Volumes/Data/Sites/ionize-with_ci2/application/../themes/demo/config/views.php */
