<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page_blog' => 'Page Blog',
    'Page_contact' => 'Page Contact',
    'page_home' => 'Page Home',
    'page_search_result' => 'Page Search Results',
  ),
  'article' => 
  array (
    'article_blog_post_detail' => 'Blog Post',
    'article_blog_post_list' => 'Blog Post List',
    'article_footer_twitter' => 'Footer Twitter',
  ),
);


/* End of file views.php */
/* Auto generated by Themes Administration on : 2011.07.27 08:10:48 */
/* Location: /var/www/application/../themes/demo/config/views.php */
