<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page_blog_view_post' => 'Blog Post view',
    'page_blog_view' => 'Blog view',
    'page' => 'Page',
  ),
);


/* End of file views.php */
/* Auto generated by Themes Administration on : 2012.09.21 10:42:49 */
/* Location: /Users/Partikule/Sites/02.Test/ionize-ftl/application/../themes/ftl/config/views.php */
