<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$config['protocol'] = "smtp";
$config['mailpath'] = "/usr/sbin/sendmail";
$config['smtp_host'] = "";
$config['smtp_user'] = "";
$config['smtp_pass'] = "";
$config['smtp_port'] = "25";
$config['mailtype'] = "html";
$config['charset'] = "utf-8";


/* End of file email.php */
/* Auto generated by Settings Administration on : 2009.12.20 16:28:59 */
/* Location: ./application/config/email.php */
