<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
| -------------------------------------------------------------------
| IONIZE LANGUAGES
| -------------------------------------------------------------------
| Contains the available languages definitions for the front-end.
| Auto-generated by Ionizes Language administration.
|
| IMPORTANT : 
| This file has no impact on ionizes admin languages.
| For Admin languages modification, see application/languages/  
|
*/

// default language abbreviation
$config['language_abbr'] = 'en';

// available languages
$config['lang_uri_abbr'] = array(
	'en' => 'english'
	);

// ignore these language abbreviation : not used for the moment 
$config['lang_ignore'] = array();


/* End of file language.php */
/* Auto generated by Ionize Installer on : 2010.12.08 14:58:58 */
/* Location: ./application/config/language.php */
