<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed'); 

$modules = array(
	);

$aliases = array(
	);

$disable_controller = array(

	);



/* End of file modules.php */
/* Auto generated by Themes Administration on : 2011.06.09 18:51:51 */
/* Location: application//config/modules.php */
