<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed'); 

$modules = array(
	'fancyupload' => 'Fancyupload',
	'search' => 'Search',
	'users' => 'Usermanager',
	'eventcalendar' => 'Eventcalendar',
	'paypal' => 'Paypal',
	'demo' => 'Demo'
	);

$aliases = array(

	);



/* End of file modules.php */
/* Auto generated by Themes Administration on : 2011.06.08 22:21:13 */
/* Location: application//config/modules.php */
