<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed'); 

$modules = array(
	'fancyupload' => 'Fancyupload',
	'search' => 'Search',
	'users' => 'Usermanager'
	);

$aliases = array(

	);



/* End of file modules.php */
/* Auto generated by Themes Administration on : 2010.12.20 11:11:36 */
/* Location: application//config/modules.php */
