<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'article' => 
  array (
    'articles/ajaxform' => 'Ajax Form',
  ),
  'page' => 
  array (
    'page_blog' => 'Blog',
    'page_blog_post' => 'Blog Post',
    'page_contact' => 'Contact',
    'page_home' => 'Home',
    'page_my_account' => 'My Account',
    'page' => 'Page',
  ),
);


/* Auto generated by Themes Administration on : 2013.06.02 11:39:39 */
