<?php 

$config['fancyupload_active'] = '';
$config['fancyupload_max_upload'] = '0';
$config['fancyupload_type'] = 'photoqueue';
$config['fancyupload_folder'] = dirname(BASEPATH).'/files/';
$config['fancyupload_file_prefix'] = '';
$config['fancyupload_send_alert'] = '';
$config['fancyupload_send_confirmation'] = '';
$config['fancyupload_email'] = '';
$config['fancyupload_group'] = '1';


/* End of file config.php */
/* Auto generated by FancyUpload Administration on : 2011.01.27 20:00:45 */
/* Location: modules/Fancyupload/config/config.php */
